on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clean Cache
        run: yarn cache clean

      # - name: Switch to Production
      #   run: export NODE_ENV="production"

      - name: Install prod dependencies
        run: yarn install

      - name: Check installed packages
        run: yarn list
      
      - name: Check ray
        run: yarn ray --help
      
      - name: Check directory
        run: ls -a
  
      - name: Build project
        run: yarn run build

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: dist
      
